### ISSUE TITLE
_is_accelerate_prepared issue

### ISSUE THREAD

**Issue by spyroot** [huggingface/accelerate#1574]
### System Info

Hi Folks,

I was running code and upgrading for three days. Keep hitting this issue.

Before that, it was the only way I manage to run it. (where both are Torch Dataloader)
```python
self.model, self.optimizer, train_dataloader, eval_dataset = accelerator.prepare(
            [self.model, self.optimizer, train_dataloader, eval_dataset],
            device_placement=[True])
```

Note that in many examples in docs, you provide different examples, but in practice, I think you need to handle a bit more concrete.

Now I see in the code you patch 
AttributeError: 'list' object has no attribute '_is_accelerate_prepared'
Now the question is a list of 4 elements, of course, that will fail.

Now if I do
```
  self.model, self.optimizer, train_dataloader, eval_dataset = accelerator.prepare(
            self.model, self.optimizer, train_dataloader, eval_dataset,
            device_placement=[True, True, True, True])"
```
It does work. It blocks inside, prepares to hit 100, and never returns.

Now why did I in the beginning (i.e, in the version I had before) [x,y,z,w]

Because of this, in prepare.
```
  result = tuple(
      self._prepare_one(obj, first_pass=True, device_placement=d) 
  for obj, d in zip(args, device_placement)
  )
  result = tuple(self._prepare_one(obj, device_placement=d) 
for obj, d in zip(result, device_placement))
```

### Information

- [ ] The official example scripts
- [x ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

  self.model, self.optimizer, train_dataloader, eval_dataset = accelerator.prepare(
            [self.model, self.optimizer, train_dataloader, eval_dataset],
            device_placement=[True])"
            
It will try to set attr on the list
           

### Expected behavior

It is not clear what it is trying to do, I tried to understand why when I do   

self.model, self.optimizer, train_dataloader, eval_dataset = accelerator.prepare(
            self.model, self.optimizer, train_dataloader, eval_dataset,
            device_placement=[True, True, True, True])"
            
 Just block.

**Comment by muellerzr** [comment]
You must prepare dataloaders, models, optimizers, and schedulers. Preparing datasets will not do anything/should not be done. We can add a bit of a guard here potentially, as `_is_accelerate_prepared` is new, however that is the direct issue with your code.

**Comment by muellerzr** [comment]
For 1, that's always an option. You never need to prepare everything if you handle some things yourself case by case

Since we can pass in multiple models etc, the list method exists since it must be in the same order as what is being passed in. We don't care about *what* that thing is nor can we since you can prepare multiple models, multiple optimizers, etc, etc. `**kwargs` shouldn't really be used with `prepare` also, since it only has `*args` and `device_placement` (so there's only one true "kwarg" here). So I'm not quite sure I agree with the solution here you've mentioned yet, as that's more user behavioral issues we probably can/should guard against.
