### ISSUE TITLE
multi-GPU is not available 

### ISSUE THREAD

**Issue by huang624** [huggingface/accelerate#707]
### System Info
```
- `Accelerate` version: 0.12.0
- Platform: Linux-5.4.0-72-generic-x86_64-with-glibc2.27
- Python version: 3.8.6
- Numpy version: 1.23.2
- PyTorch version (GPU?): 1.12.1+cu102 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - main_process_ip: None
        - main_process_port: None
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - downcast_bf16: no

```

### Information
- [ ] The official example scripts
- [x] My own modified scripts

### Tasks
- [x] One of the scripts in the examples/ folder of Accelerate or an officially supported no_trainer script in the examples folder of the transformers repo (such as run_no_trainer_glue.py)
**Task: QNLI in Glue**
**Model: BERT**
- [ ] My own task or dataset

### Reproduction
I have 3 GPU with my container, and I would like to use GPU[0] and GPU[2] to train model.  
Unfortunately, it will use single gpu only when the model training.

<img src="https://user-images.githubusercontent.com/88367016/191441822-69a451a1-67b7-4279-ae1a-6feb16e8e987.png" width=60% height=60%>

command line of launch my script:
```
accelerate config
python myscript.py
```

code:
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2, 0'
import torch
from datasets import load_dataset
import pandas as pd
from transformers import BertTokenizerFast
from torch.utils import data

from transformers import BertConfig, BertForSequenceClassification
import logging
import datasets
from datasets import load_dataset, load_metric
from torch.utils.data import DataLoader
from tqdm.auto import tqdm, trange
import math

import transformers
from accelerate import Accelerator
from transformers import (
    AdamW,
    AutoConfig,
    default_data_collator,
    get_scheduler
)


def add_targets(encodings, label):
    encodings.update({'label': label})

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings):
        self.encodings = encodings

    def __getitem__(self, idx):
        return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}

    def __len__(self):
        return len(self.encodings.input_ids)

# train_batch_size = 8, eval_batch_size = 10, num_train_epochs = 3
def get_dataloaders(train_batch_size, eval_batch_size, num_train_epochs):
    data_collator = default_data_collator
    train_dataloader = DataLoader(train_dataset, shuffle=True, collate_fn=data_collator, batch_size=train_batch_size)
    eval_dataloader = DataLoader(eval_dataset, collate_fn=data_collator, batch_size=eval_batch_size)
    
    return train_dataloader, eval_dataloader

def training(model):
    train_batch_size = 8
    eval_batch_size = 10
    num_train_epochs = 3
    train_dataloader, eval_dataloader = get_dataloaders(train_batch_size, eval_batch_size, num_train_epochs)
    learning_rate=3e-5         
    gradient_accumulation_steps = 1   

    no_decay = ["bias", "LayerNorm.weight"]
    optimizer_grouped_parameters = [
        {
            "params": [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)],
            "weight_decay": 0.0,
        },                                
        {
            "params": [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)],
            "weight_decay": 0.0,
        },
    ]
    optimizer = AdamW(optimizer_grouped_parameters, lr=learning_rate)

    # Scheduler and math around the number of training steps.
    num_update_steps_per_epoch = math.ceil(len(train_dataloader) / gradient_accumulation_steps)
    max_train_steps = num_train_epochs * num_update_steps_per_epoch
    print('max_train_steps', max_train_steps)

    # scheduler
    lr_scheduler = get_scheduler(
        name="linear",
        optimizer=optimizer,
        num_warmup_steps=0,
        num_training_steps=max_train_steps,
    )

    # Initialize the accelerator. We will let the accelerator handle device placement for us in this example.
    accelerator = Accelerator(split_batches = True)

    
    # Prepare everything with our `accelerator`.
    model, optimizer, train_dataloader, eval_dataloader = accelerator.prepare(
        model, optimizer, train_dataloader, eval_dataloader
    )

    # Train!
    logger = logging.getLogger(__name__)
    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO,
    )
    logger.info(accelerator.state)
    output_dir = '/user_data/test'  # your folder


    total_batch_size = train_batch_size * accelerator.num_processes * gradient_accumulation_steps

    logger.info("***** Running training *****")
    logger.info(f"  Num examples = {len(train_dataset)}")
    logger.info(f"  Num Epochs = {num_train_epochs}")
    logger.info(f"  Instantaneous batch size per device = {train_batch_size}")
    logger.info(f"  Total train batch size (w. parallel, distributed & accumulation) = {total_batch_size}")
    logger.info(f"  Gradient Accumulation steps = {gradient_accumulation_steps}")
    logger.info(f"  Total optimization steps = {max_train_steps}")


    completed_steps = 0
    best_epoch = {}

    for epoch in trange(num_train_epochs, desc="Epoch"):
        model.train()
        for step, batch in enumerate(tqdm(train_dataloader, desc="Iteration")):
            outputs = model(**batch)
            loss = outputs.loss
            loss = loss / gradient_accumulation_steps
            accelerator.backward(loss)
            if step % gradient_accumulation_steps == 0 or step == len(train_dataloader) - 1:
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()
                completed_steps += 1

            if step % 50 == 0:
                print({'epoch': epoch, 'step': step, 'loss': loss.item()})

            if completed_steps >= max_train_steps:
                break
            

        if output_dir is not None:
            accelerator.wait_for_everyone()
            unwrapped_model = accelerator.unwrap_model(model)
            unwrapped_model.save_pretrained(output_dir + '/' + 'epoch_' + str(epoch), save_function=accelerator.save)

if __name__ == '__main__':
    datasets = load_dataset('glue', 'qnli')

    train_data = pd.DataFrame(datasets['train']).drop(columns = ['idx'])
    validation_data = pd.DataFrame(datasets['validation']).drop(columns = ['idx'])
    test_data = pd.DataFrame(datasets['test']).drop(columns = ['idx'])

    train_question, train_sentence, train_label = train_data['question'][0:25000].tolist(), train_data['sentence'][0:25000].tolist(), train_data['label'][0:25000].tolist()
    eval_question, eval_sentence, eval_label = validation_data['question'][0:3000].tolist(), validation_data['sentence'][0:3000].tolist(), validation_data['label'][0:3000].tolist()
    tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased', model_max_length=128)

    train_encodings = tokenizer(train_question, train_sentence, padding='max_length', truncation=True)
    eval_encodings = tokenizer(eval_question, eval_sentence, padding='max_length', truncation=True)

    add_targets(train_encodings, train_label)
    add_targets(eval_encodings, eval_label)

    train_dataset = Dataset(train_encodings)
    eval_dataset = Dataset(eval_encodings)

    config = BertConfig.from_pretrained('bert-base-uncased', num_labels=2)
    model = BertForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

    training(model)
```
### Expected behavior
```
Use two GPU for training
```

**Comment by sgugger** [comment]
As instructed in the template, please let us know how you launched your script.

**Comment by huang624** [comment]
Hi,@sgugger 
The issue is sloved by myself! However, I still have a question about it.

I launched my script with the command line of  ```python my_script.py``` before because I read the document [here](https://github.com/huggingface/accelerate#launching-script). 
It mentioned that ```This CLI tool is optional, and you can still use python my_script.py or python -m torch.distributed.launch my_script.py at your convenance.```, but it use single gpu only when the model was training. 


In other words, multi GPU is not available when I launched my script with command line of 
```
accelerate config
python my_script.py
```
, and it is available below.
```
accelerate config
accelerate launch my_script.py
```

I wonder that it is a bug of accelerate or there is a misunderstanding when I read the document. 
Thanks a lot!

**Comment by sgugger** [comment]
`python script.py` does not handle multiple GPUs. You need to launch the script once per GPU, which is why PyTorch developped a tool `python -m torch.distributed.launch my_script.py` (or now `python -m torch.distributed.run my_script.py`).

Accelerate makes it easier by regrouping all of this inside a single command `accelerate launch` that will call the right launcher depending on the number of GPUs you selected. Of course, you're free to not use it but then you need to use the right launcher yourself. Is this clearer?

**Comment by huang624** [comment]
Hi, @sgugger 
It is so clear! Thank you for your explanation!
